-- Kontenplan Import aus DATEV - Version 2 (Deadlock-sicher)
-- Generiert am 2026-07-29
-- ANLEITUNG: Führe die 3 Teile NACHEINANDER aus (nicht alle auf einmal!)

-- ========================================
-- TEIL 1: Tabelle erstellen
-- ========================================

CREATE TABLE IF NOT EXISTS konto_bezeichnungen (
    konto_nr TEXT PRIMARY KEY,
    beschreibung_it TEXT,
    beschreibung_de TEXT,
    typ TEXT,
    ist_summe BOOLEAN DEFAULT false
);

-- ========================================
-- TEIL 2: Daten einfügen (nach Teil 1 ausführen!)
-- ========================================

INSERT INTO konto_bezeichnungen (konto_nr, beschreibung_it, beschreibung_de, typ, ist_summe) VALUES
    ('600', 'Ricavi delle vendite e delle prestazioni', 'Erlöse aus Lieferungen u. Leistungen', 'R', true),
    ('60010', 'Cessioni di beni cui è diretta attività', 'Veräußerungen der Betriebstätigk.', 'R', false),
    ('6001010', 'Ricavi per vendite Italia', 'Erlöse aus Verkauf', 'R', false),
    ('600101010', 'Ricavi per vendite Shop - E', 'Erlöse Shop - W', 'R', false),
    ('600101015', 'Ricavi da corrispettivi, aggi e altro', 'Umsatzerlöse (Erl.aus Quittungen), Agio und Sonstiges', 'R', false),
    ('60010101550', 'Corrispettivi locazione bar - E', 'Erlöse Verpachtung bar - W', 'R', false),
    ('60010101551', 'Rimborsi spese locazione bar - E', 'Spesenrückerstattung Verpachtung bar - W', 'R', false),
    ('600101051', 'Ricavi per vendite Shop Biennale Venezia', 'Erlöse Shop Biennale Venedig', 'R', false),
    ('60015', 'Prestazione di servizi cui è dir. att.', 'Leistungen der Betriebstätigk.', 'R', false),
    ('6001510', 'Ricavi per prestazioni Italia', 'Erlöse Dienstleistungen ', 'R', false),
    ('600151051', 'Ricavi esposizioni - E', 'Erlöse Austellungen - W', 'R', false),
    ('600151052', 'Altri ricavi - E', 'Sonstige Erlöse - W', 'R', false),
    ('600151053', 'Ricavi pubblicita`- E', 'Erlöse aus Werbetätigkeit - W', 'R', false),
    ('600151055', 'Ricavi per formazione e mediazione', 'Erlöse Bildung und Vermittlung', 'R', false),
    ('600151060', 'Ricavi pubblicita`Biennale Venezia', 'Erlöse aus Werbetätigkeit Biennale Venedig', 'R', false),
    ('600151061', 'Ricavi esposizioni Biennale Venezia', 'Erlöse Ausstellung Biennale Venedig', 'R', false),
    ('600151063', 'Ricavi per eventi Biennale Venezia', 'Erlöse Veranstaltungen Biennale Venedig', 'R', false),
    ('640', 'Altri ricavi e proventi', 'Sonstige betriebliche Erträge', 'R', true),
    ('64003', 'Riaddebiti vari', 'Sonstige Zurückbelastungen', 'R', false),
    ('6400335', 'Rimborsi spese  generico', 'Spesenrückerstattung', 'R', false),
    ('64012', 'Altri ricavi,prov.non rientr.att.gest.o.', 'Sonst. Erträge nicht der Betriebstätigk.', 'R', false),
    ('6401215', 'Abbuoni e arrotondamenti attivi', 'Rabatte u. Aufrundungen', 'R', false),
    ('6401232', 'Sopravvenienze non interamente tassabili', 'Nicht gänzlich steuerb.ausserord.Aufwend', 'R', false),
    ('640123204', 'Sopravv.attive fiscalmente non rilevanti', 'Außerord. Erträge nicht steuerpflichtig', 'R', false),
    ('6401233', 'Sopravvenienze attive ordinarie', 'Ausserordentliche Erträge', 'R', false),
    ('6401259', 'Proventi diversi', 'Sonst.Erträge', 'R', false),
    ('6401260', 'Proventi quota 5 per mille', 'Erträge Quote 5 promille', 'R', false),
    ('64015', 'Contributi in c.to esercizio', 'Sonstige Beiträge', 'R', false),
    ('6401550', 'Quota soci - I', 'Mitgliedsbeiträge - I', 'R', false),
    ('6401551', 'Erogazioni liberali - I', 'Spenden - I', 'R', false),
    ('6401552', 'Contributi Comune Merano - I', 'Beitrag Gemeinde Meran - I', 'R', false),
    ('6401554', 'Contributi Provincia Bolzano - I', 'Beitrag Provinz Bozen - I', 'R', false),
    ('6401556', 'Contributi Regione - I', 'Beitrag Region - I', 'R', false),
    ('6401557', 'Contributi Fondazione Cassa di Risp.-I', 'Beiträge Stiftung Sparkasse - I', 'R', false),
    ('6401564', 'Quota soci Biennale Venezia', 'Spenden Biennale Venedig', 'R', false),
    ('6401565', 'Contributi Venezia', 'öffentliche Beiträge Venedig', 'R', false),
    ('64017', 'Contributi in c.to impianti', 'Beiträge zur Anlage', 'R', false),
    ('6401750', 'Credito d''imposta per investimenti', 'Steuerverrechnung Credito d''imposta Investitionen', 'R', false),
    ('6401751', 'Contributi in c.to impianti imponibili', 'Investitionsbeitraege', 'R', false),
    ('680', 'Costi per materie prime, sussidiarie', 'Aufw. f. Roh- u. Hilfsstoffe', 'C', true),
    ('68007', 'Acquisto beni per produzione di servizi', 'Erw. v. Gütern zur Dienstleistungsherst.', 'C', false),
    ('6800750', 'Acquisto beni per esposizioni - M', 'Zukauf Ausstellung - G', 'C', false),
    ('6800751', 'Acquisto beni per esposiz..Bienn.Venezia', 'Zukauf Ausstellung Biennale Venedig', 'C', false),
    ('68020', 'Acquisti di materiali di consumo', 'Einkauf Verbrauchsmaterial', 'C', false),
    ('6802010', 'Acquisti di materiali di consumo prod.', 'Einkauf Verbrauchsmaterial - Erzeugnisse', 'C', false),
    ('680201010', 'Acquisti di materiali di consumo prod.', 'Einkauf Verbrauchsmaterial - Erzeugnisse', 'C', false),
    ('6802025', 'Acquisti materiali di consumo manutenz.', 'Einkauf Verbrauchsmat. f. Instandhaltung', 'C', false),
    ('680202530', 'Cancelleria e stampati', 'Büromaterial', 'C', false),
    ('6802030', 'Acquisti di altri materiali di consumo', 'Einkauf sonstiger Verbrauchsmaterial', 'C', false),
    ('680203024', 'Materiale ufficio - igiene e pulizia', 'Einkauf  Reinigungsmittel', 'C', false),
    ('680203050', 'Acquisto fiori e decorazioni', 'Zukauf Blumen und Dekorationmaterial', 'C', false),
    ('68025', 'Acquisti di merci e prodotti finiti', 'Waren- und fertiger Erzeugnisse Einkauf', 'C', false),
    ('6802510', 'Acquisti di merci Shop - E', 'Zukauf Shop - W', 'C', false),
    ('6802520', 'Acquisti di beni <= € 516,46 ded. 100%', '100% abziehbarer Güter Einkauf<=€ 516,46', 'C', false),
    ('6802552', 'Acquisti di merci Shop Biennale Venezia', 'Zukauf Shop Venedig', 'C', false),
    ('690', 'Costi per servizi', 'Aufw. f. Dienstleistungen', 'C', true),
    ('69012', 'Costi altri servizi', 'Aufwendungen sonstige Dienstleistungen', 'C', false),
    ('6901201', 'Costi altri servizi', 'Aufwendungen sonstige Dienstleistungen', 'C', false),
    ('6901230', 'Altri oneri di gestione', 'Sonstige betriebliche Aufwendungen', 'C', false),
    ('6901251', 'Spese per esposizioni - M', 'Dienstleistung Ausstellung - G', 'C', false),
    ('6901252', 'Spese per cataloghi - M', 'Dienstleistung Kataloge - G', 'C', false),
    ('6901253', 'Spese per progetti - M', 'Dienstleistung Projekte - G', 'C', false),
    ('6901254', 'Servizi di lavanderia biancheria', 'Reinigung Wäsche', 'C', false),
    ('6901257', 'Servizi per progetto Biennale Venezia', 'Dienstleistung Projekte Venedig', 'C', false),
    ('69015', 'Costi per servizi di manutenzione', 'Aufw. f. Instandhaltung Dienstleistungen', 'C', false),
    ('6901510', 'Canoni periodici di manutenzione', 'Periodischer Instandhaltungspreis', 'C', false),
    ('690151020', 'Canoni periodici di manut. attrezz. - M', 'Periodische Wartung - G', 'C', false),
    ('6901515', 'Spese di manutenzione', 'Instandhaltungsaufwand', 'C', false),
    ('690151520', 'Spese manutenz. attrezzature', 'Instandhalt.-aufwand Ausstattung', 'C', false),
    ('690151527', 'Spese manutenz. altri beni telefonia - M', 'Instandhaltung Telefon - G', 'C', false),
    ('6901525', 'Altre spese di manutenzione', 'Sonstiger Instandhaltungsaufwand', 'C', false),
    ('690152510', 'Riparazioni e manutenzioni diverse', 'Sonst.Reparatur- Instandhaltungsaufwand', 'C', false),
    ('690152520', 'Manutenzioni su beni di terzi ded. 100%', 'Instandhaltung Güter Dritter', 'C', false),
    ('690152550', 'Riparazioni e manut.macchine ufficio', 'Instandh.Büromaschinen - G', 'C', false),
    ('690152551', 'Riparazioni e manutenzioni Bar', 'Instandhaltung und Reparatur Bar', 'C', false),
    ('69018', 'Costi per servizi di consulenza', 'Beratungskosten', 'C', false),
    ('6901815', 'Consulenze e prestazioni commerciali', 'Handelsberatung u. -leistungen', 'C', false),
    ('690181520', 'Onorario a intermediari', 'Honorare Vermittler', 'C', false),
    ('6901820', 'Consulenze legali, fiscali ed amministr.', 'Rechts- Steuer u. Verwaltungsberatung', 'C', false),
    ('690182025', 'Consulenza fiscale e societaria', 'Wirtschafts- und Steuerberatung', 'C', false),
    ('690182037', 'Amministrazione e paghe', 'Verwaltung + Lohnspesen', 'C', false),
    ('690182040', 'Collaborazioni occasionali aff. attività', 'Gelegentliche Mitarbeit', 'C', false),
    ('690182048', 'Contributi INPS su coll.occas.afferenti', 'Sozialabg. geleg. Mitarb. geschäftszug.', 'C', false),
    ('6901825', 'Servizi amministrativi e finanziari', 'Verwaltungs- u. Finanzleistungen', 'C', false),
    ('690182520', 'Spese e servizi bancari (non finanziari)', 'Bankspesen', 'C', false),
    ('690182564', 'Spese e serv.bancari Venezia', 'Bankspesen Biennale Venedig', 'C', false),
    ('69021', 'Costi per servizi promozionali e pubb.', 'Aufw. f. Werbung u. Befoerderung', 'C', false),
    ('6902110', 'Pubblicità e propaganda', 'Werbung', 'C', false),
    ('6902150', 'Inserzioni su giornali', 'Anzeige in Zeitungen', 'C', false),
    ('6902152', 'Servizi online marketing', 'Online Marketing', 'C', false),
    ('6902153', 'Pubblicità e propaganda Venezia', 'Werbung Venedig', 'C', false),
    ('69024', 'Costi per servizi generali e utenze', 'Versorgungskosten', 'C', false),
    ('6902410', 'Costi per servizi di utenze', 'Versorgungskosten', 'C', false),
    ('690241003', 'Somministrazione energia elettrica - M', 'Strom - G', 'C', false),
    ('690241006', 'Spese telefoni/fax - M', 'Telefon und Fax - G', 'C', false),
    ('690241009', 'Spese telefoni cellulari', 'Mobiltelefon', 'C', false),
    ('690241015', 'Spese postali e bollati', 'Post u. Briefmarken', 'C', false),
    ('690241021', 'Somministrazione gas - M', 'Gas - G', 'C', false),
    ('690241024', 'Fornitura acqua - M', 'Wasser - G', 'C', false),
    ('690241065', 'Spese telef. cellulari Biennale Venezia', 'Mobiltelefon Biennale Venedig', 'C', false),
    ('6902415', 'Assicurazioni', 'Versicherung', 'C', false),
    ('690241524', 'Altre assicurazioni deducibili - M', 'Versicherungen - G', 'C', false),
    ('690241550', 'Assicurazioni Biennale Venezia', 'Versicherungen Biennale Venedig', 'C', false),
    ('6902420', 'Altri servizi generali', 'Sonstige Dienstleistungen', 'C', false),
    ('690242010', 'Servizi di pulizia', 'Reinigungsdienste', 'C', false),
    ('6902425', 'Compensi amministratori e sindaci', 'Gehälter Geschäftsf.,Aufsichtsratsmitgl.', 'C', false),
    ('690242541', 'Contributi INAIL amministratori/collabor', 'Verb.Inail Freie Mitarbeiter Co.co.co', 'C', false),
    ('69027', 'Costi per servizi ai dipendenti', 'Aufw. f. Leistungen Arbeitnehmer', 'C', false),
    ('6902710', 'Corsi e perfezionamento', 'Kurse und Weiterbildung', 'C', false),
    ('6902725', 'Servizi mensa o ticket restaurant', 'Betriebskantine o. Essenmarken', 'C', false),
    ('6902730', 'Visite mediche dipendenti', 'Aerztliche Untersuchungen Arbeitnehmer', 'C', false),
    ('69033', 'Costi viaggi, soggiorni e rappresentanza', 'Reise-,Aufenthalts- u. Aufwandskosten', 'C', false),
    ('6903310', 'Spese viaggio dipendenti e cococo', 'Arbeitn./Cococo-Reisekosten', 'C', false),
    ('6903312', 'Altre spese di viaggio artisti', 'Sonstige Reisekosten Künstler', 'C', false),
    ('6903315', 'Altre spese vitto e alloggio 75%', 'Unterkunft und Verpflegung 75%', 'C', false),
    ('6903316', 'Spese vitto e alloggio artisti/stampa', 'Unterkunft u.Verpflegung Künstler/Presse', 'C', false),
    ('6903320', 'Spese di rappresentanza deducibili', 'Repräsentationsspesen abzugsfähig', 'C', false),
    ('6903351', 'Spese di rappresent.ded.pubblicazioni', 'Repräsentationsspesen abzugsfähig Publikationen', 'C', false),
    ('6903352', 'Spese di rappr.ded. biennale Venezia', 'Repräsentationsspesen abzugsfähig Biennale Venedig', 'C', false),
    ('6903353', 'Altre spese di viaggio artisti bienn.Ven', 'Sonstige Reisekosten Künstler Biennale Venedig', 'C', false),
    ('6903354', 'Altre spese vitto e all.100% bienn.Venez', 'Unterkunft und Verpflegung Biennale Venedig', 'C', false),
    ('700', 'Costi per godimento beni di terzi', 'Aufw. f. Nutzung fremder Güter', 'C', true),
    ('70010', 'Affitti, locazioni e oneri accessori', 'Miete, Pracht u. sonstige Aufw.', 'C', false),
    ('7001010', 'Affitti Caffe`Kunsthaus', 'Miete Cafe`Kunsthaus', 'C', false),
    ('7001020', 'Spese condominiali - M', 'Mietnebenkosten - G', 'C', false),
    ('7001052', 'Affitto area espositiva', 'Miete Ausstellungsbereich', 'C', false),
    ('7001053', 'Affitto ufficio', 'Miete Büro', 'C', false),
    ('7001054', 'Affitti', 'Miete', 'C', false),
    ('7001055', 'Affitti spazio espositivo Bienn.Venezia', 'Miete Ausstellungsfläche Biennale Venedig', 'C', false),
    ('70015', 'Noleggi/costi godimento auto', 'Miete/Kosten PKW-Nutzung', 'C', false),
    ('7001520', 'Noleggi/costi godimento auto non strum.', 'Miete/Kosten PKW', 'C', false),
    ('70040', 'Altri costi per godimento beni di terzi', 'Sonstige Aufw. f. Nutzung fremde Güter', 'C', false),
    ('7004030', 'Costi period.i licenza d''uso software -M', 'Software dauer 1 Jahr - G', 'C', false),
    ('710', 'Costi per il personale', 'Personalaufwand', 'C', true),
    ('71010', 'Salari e stipendi', 'Löhne u. Gehälter', 'C', false),
    ('7101010', 'Retribuzione del personale dipendente', 'Personalspesen', 'C', false),
    ('7101045', 'Arrot. att./pass. su retribuz.', 'Aufrund.u.Abrundungen a.Löhne u.Gehälter', 'C', false),
    ('71015', 'Oneri sociali e previdenziali', 'Sozialabgaben u. Fürsorgebeiträge', 'C', false),
    ('7101510', 'Oneri sociali personale', 'Sozialabgaben Personal', 'C', false),
    ('7101517', 'Altri enti previdenziali e assistenziali', 'Sonst. Sozialversicherungsträger', 'C', false),
    ('710151715', 'Contributi Fondo EST', 'EST Rückst. Beiträge', 'C', false),
    ('710151720', 'Contributi Enti bilaterali', 'Beiträge Bilaterale Körperschaft', 'C', false),
    ('7101520', 'INAIL', 'INAIL', 'C', false),
    ('71020', 'Trattamento di fine rapporto', 'Abfertigung', 'C', false),
    ('7102010', 'T.F.R. personale accantonato', 'Zuführung Abfertigungsfond', 'C', false),
    ('71025', 'Trattamento di quiescenza e simili', 'Personalsabfindung, ähnliche Verpflicht.', 'C', false),
    ('7102520', 'Contributi a forme pensionistiche compl.', 'Beiträge Zusatzrentenfond', 'C', false),
    ('71030', 'Altri Costi', 'Sonstige Kosten', 'C', false),
    ('7103024', 'Omaggi ai dipendenti', 'Geschenke f. Arbeitnehmer / Firmenessen', 'C', false),
    ('720', 'Ammortamenti e svalutazioni', 'Abschreibungen u. Abwertungen', 'C', true),
    ('72015', 'Amm.to immobilizzazioni materiali', 'Absch. a. Sachanlagen', 'C', false),
    ('7201510', 'Amm.to ordinario immob. materiali', 'Ordentliche Absch. a. Sachanlagen', 'C', false),
    ('720151015', 'Amm.to ordinario impianti e macch.', 'Ordentl. Absch.a.techn.Anlagen,Maschinen', 'C', false),
    ('720151025', 'Amm.to ordinario altri beni', 'Ordentliche Absch.a.sonstige Sachanlagen', 'C', false),
    ('720151029', 'Ammortamento altri beni non deducibili', 'Abschreib.a.and.Güter nicht abschreibbar', 'C', false),
    ('730', 'Variazioni riman. materie prime, suss.', 'Bestandsveraenderung Roh- u. Hilfsstoffe', 'C', true),
    ('73025', 'Variazioni rimanenze merci', 'Warenbestandsveränderung', 'C', false),
    ('7302510', 'Rimanenze iniziali merci', 'Warenanfangsbestand', 'C', false),
    ('7302515', 'Rimanenze finali merci', 'Warenendbestand', 'C', false),
    ('7302552', 'Rimanenze iniziali cataloghi e libri', 'Anfangsbestand Kataloge u.Bücher', 'C', false),
    ('7302554', 'Rimanenze finali cataloghi e libri', 'Warenendbestand Kataloge u.Bücher', 'C', false),
    ('760', 'Oneri diversi di gestione', 'Sonstige betriebliche Aufwendungen', 'C', true),
    ('76010', 'Imposte e tasse non relative al reddito ', 'Steuer u. Gebuhren nicht auf Einkommen', 'C', false),
    ('7601010', 'Imposte di registro ipotecarie catastali', 'Eintragungsgeb. Hypothekst.Grundbuchgeb.', 'C', false),
    ('760101010', 'Imposta di registro - M', 'Registergebühren - G', 'C', false),
    ('7601015', 'Imposta di bollo', 'Stempelgebühr', 'C', false),
    ('760101510', 'Imposta di bollo - M', 'Stempelgebühr - G', 'C', false),
    ('7601025', 'Tasse per la finanza locale', 'Gebühren f. Gemeindefinanzen', 'C', false),
    ('760102515', 'Tassa smaltimento rifiuti', 'Gebühr f. Abfallbeseitigung', 'C', false),
    ('760102520', 'Imposta comunale pubblicità esterna', 'Gemeindest. Plakatwerb. äusserl.Schilder', 'C', false),
    ('760102525', 'Diritto sulle pubbliche affissioni', 'Konzession auf Plakate u. Anschlaege', 'C', false),
    ('7601035', 'Altre imposte e tasse ', 'Sonstige Steuern u. Gebühren', 'C', false),
    ('760103510', 'Altre imposte e tasse ', 'Sonstige Steuern u. Gebühren', 'C', false),
    ('760103525', 'IVA indetraibile per pro/rata', 'MwSt.- teilweise nicht abziehbar (pro rata)', 'C', false),
    ('760103550', 'Quota S.I.A.E. - M', 'S.I.A.E. Gebühren - G', 'C', false),
    ('760103551', 'IVA indetraibile per pro/rata Venezia', 'Mwst.-teilweise nicht abziehbar Venedig (pro rata)', 'C', false),
    ('76015', 'Periodici, pubblicazioni e quote assoc.', 'Zeitschrift.,Veröffentlh.,Vereinbeiträge', 'C', false),
    ('7601510', 'Quote associative', 'Mitgliedsbeiträge', 'C', false),
    ('7601520', 'Abbonamenti e pubblicazioni', 'Abonnemente, Zeitschriften und Bücher', 'C', false),
    ('76020', 'Altri oneri di gestione', 'Sonstige betriebliche Aufwendungen', 'C', false),
    ('76020015', 'Spese camerali, catastali e diritti vari', 'Handelskammergeb.,Grundbuchgeb.ähnliches', 'C', false),
    ('76020020', 'Spese diritti doganali', 'Zollgebühren', 'C', false),
    ('76020025', 'Multe e ammende', 'Straf- u. Bussgeld', 'C', false),
    ('76020104', 'Sopravvenienze passive indeducibili', 'Periodenfremde Aufwände', 'C', false),
    ('76020107', 'Altre sopravvenienze passive', 'Sonstige ausserordentliche Aufwendungen', 'C', false),
    ('76020120', 'Altri oneri di gestione non ded.', 'Nicht abzugsfähige Aufwände', 'C', false),
    ('76020500', 'Arr. passive', 'Rundungsaufwände', 'C', false),
    ('76020501', 'Ritenute su interessi attivi', 'Steuerabzuege auf Zinsen', 'C', false),
    ('840', 'Proventi diversi dai precedenti', 'Sonstige Erträge', 'R', true),
    ('84015', 'Altri proventi finanz. diversi dai prec.', 'Sonst. fin. Erträge', 'R', false),
    ('8401510', 'Interessi attivi bancari e postali', 'Zinserträge K/K', 'R', false),
    ('850', 'Interessi ed altri oneri finanziari', 'Zinsen u. ähnliche  Aufw.', 'C', true),
    ('85015', 'Altri interessi ed oneri finanziari', 'Kreditkartenspesen', 'C', false),
    ('85015040', 'Interessi di mora verso fornitori', 'Verzugszinsen an Lieferanten', 'C', false),
    ('85015050', 'Interessi indeducibili IVA trimestrale', 'Nicht abziehb. Zinsen trim. MwSt.-Abrrechnung', 'C', false),
    ('85015052', 'Interessi da ravvedimenti operosi', 'Zinsen Ratenzahl.u.Regolarisierung', 'C', false),
    ('85015053', 'Interessi passivi su depositi bancari ', 'Passivzinsen auf Bankkontokorrent', 'C', false),
    ('85015090', 'Commissioni per fideiussioni bancarie', 'Kommissionen f. Bankbürgschaften', 'C', false)
ON CONFLICT (konto_nr) DO UPDATE SET
    beschreibung_it = EXCLUDED.beschreibung_it,
    beschreibung_de = EXCLUDED.beschreibung_de,
    typ = EXCLUDED.typ,
    ist_summe = EXCLUDED.ist_summe;

-- ========================================
-- TEIL 3: RLS aktivieren (nach Teil 2 ausführen!)
-- ========================================

ALTER TABLE konto_bezeichnungen ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view konto_bezeichnungen" ON konto_bezeichnungen;
CREATE POLICY "Users can view konto_bezeichnungen"
    ON konto_bezeichnungen FOR SELECT
    TO authenticated
    USING (true);

DROP POLICY IF EXISTS "Users can insert konto_bezeichnungen" ON konto_bezeichnungen;
CREATE POLICY "Users can insert konto_bezeichnungen"
    ON konto_bezeichnungen FOR INSERT
    TO authenticated
    WITH CHECK (true);

DROP POLICY IF EXISTS "Users can update konto_bezeichnungen" ON konto_bezeichnungen;
CREATE POLICY "Users can update konto_bezeichnungen"
    ON konto_bezeichnungen FOR UPDATE
    TO authenticated
    USING (true)
    WITH CHECK (true);
